baseURL = "https://xts.wtf"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "XepTion Studios - Coming soon" 
    description = "Countdown to greatness"
    favicon = ""
    message = "COMING SOON!" 
    release = "November 30, 2024" 
    background = "" 

socialIcons = [
    {name = "email", url = "example@example.com"},      
    {name = "twitter", url = "https://twitter.com/"},    
    {name = "facebook", url = "https://facebook.com/"},    
    {name = "github", url = "https://github.com/"},    
    {name = "instagram", url = "https://instagram.com/"},    
    {name = "tiktok", url = "https://tiktok.com/"},    
    {name = "linkedin", url = "https://linkedin.com/"},    
] 

[params.twitter]
	enable = false 
	username = "mansoorbarri"
